const activities = [
  {
    name: "Red Rocks Amphitheatre",
    id: 1001,
    trail: "Red Rocks Trail",
    type: "Hiking",
    location: { lat: 39.6654, lng: -105.2057 },
    difficulty: "Beginner",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
    image:
      "https://www.thewanderingqueen.com/wp-content/uploads/2022/04/Best-Hikes-In-Red-Rock-Canyon-1-of-4.jpg",
  },
  {
    name: "Garden of the Gods",
    id: 1002,
    trail: "Garden Trail",
    type: "Hiking",
    location: { lat: 38.8784, lng: -104.8694 },
    difficulty: "Intermediate",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
    image:
      "https://images.squarespace-cdn.com/content/v1/5bad2c26d74562245b63d094/1ebb4786-2ed9-43be-a105-0fbce71e7b6b/perkins+central+garden+loop+in+garden+of+the+gods",
  },
  {
    name: "Chautauqua Park",
    id: 1003,
    trail: "Chautauqua Trail",
    type: "Hiking",
    location: { lat: 40.0005, lng: -105.2817 },
    difficulty: "Beginner",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
    image:
      "https://images.squarespace-cdn.com/content/v1/534b1517e4b0b2883888bafe/709dc962-9528-481c-9869-557b4a8d1d64/Green+Mountain+Loop+Trail+Personal+Trainer.jpeg",
  },
  {
    name: "Rocky Mountain NP",
    id: 1004,
    trail: "Emerald Lake Trail",
    type: "Hiking",
    location: { lat: 40.3105, lng: -105.648 },
    difficulty: "Beginner",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
    image:
      "https://theworldtravelguy.com/wp-content/uploads/2022/10/DSCF0146_900-2.jpg",
  },
  {
    name: "Rocky Mountain NP",
    id: 1005,
    trail: "Sky Pond Trail",
    type: "Hiking",
    location: { lat: 40.3109, lng: -105.6627 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "Yes",
    camping: "Yes",
    image:
      "https://www.litaofthepack.com/wp-content/uploads/2022/06/sky-pond-views-too.jpg",
  },
  {
    name: "Manitou Springs",
    id: 1006,
    trail: "The Incline",
    type: "Hiking",
    location: { lat: 38.8577, lng: -104.9334 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
    image:
      "https://outdoorbeginner.com/wp-content/uploads/2019/11/beginners-guide-hiking-the-incline-safe-dangerous-img_2327.jpg?w=625",
  },
  {
    name: "Flatirons",
    id: 1007,
    trail: "Flatirons Loop Trail",
    type: "Hiking",
    location: { lat: 39.9999, lng: -105.2834 },
    difficulty: "Intermediate",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
    image:
      "https://www.litaofthepack.com/wp-content/uploads/2022/06/Flatirons-Boulder-768x1024.jpg",
  },
  {
    name: "Boulder",
    id: 1008,
    trail: "Bear Peak Trail",
    type: "Hiking",
    location: { lat: 39.9787, lng: -105.2954 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "No",
    gearNeeded: "No",
    camping: "No",
    image:
      "https://i.redd.it/hike-up-to-bear-peak-in-boulder-co-v0-cl6kw1n549td1.jpg?width=3024&format=pjpg&auto=webp&s=c3269ac8ee179dbec292b0957b8ca4502193da3a",
  },
  {
    name: "Eldorado Canyon",
    id: 1009,
    trail: "Rattlesnake Gulch Trail",
    type: "Hiking",
    location: { lat: 39.9332, lng: -105.2933 },
    difficulty: "Intermediate",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "No",
    image:
      "https://outdoorbeginner.com/wp-content/uploads/2014/12/fccc9-img_4681-e1598820282278.jpg?w=750",
  },
  {
    name: "Glenwood Canyon",
    id: 1010,
    trail: "Hanging Lake Trail",
    type: "Hiking",
    location: { lat: 39.5981, lng: -107.1917 },
    difficulty: "Intermediate",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "Yes",
    camping: "No",
    image:
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0c/8b/a9/81/hanging-lake.jpg?w=1200&h=-1&s=1",
  },
  {
    name: "Mount Evans Wilderness",
    id: 1011,
    trail: "Mount Bierstadt Trail",
    type: "Hiking",
    location: { lat: 39.582, lng: -105.6438 },
    difficulty: "Hard",
    elevationGain: null,
    entrancePass: "Yes",
    gearNeeded: "Yes",
    camping: "Yes",
    image:
      "https://trailrunproject.com/assets/photos/hike/7001090_smallMed_1554217633.jpg?cache=1751713890",
  },
  {
    name: "Maroon Bells",
    id: 1012,
    trail: "Maroon Bells Scenic Loop Trail",
    type: "Hiking",
    location: { lat: 39.0986, lng: -106.9414 },
    difficulty: "Beginner",
    elevationGain: "160 ft",
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
    image:
      "https://images.squarespace-cdn.com/content/v1/5f39599f0dd69335c3379b81/1674519907616-2I838PY2GL98GN85K6NH/unsplash-image--sUgs6NLFpE.jpg",
  },
  {
    name: "Rocky Mountain NP",
    id: 1013,
    trail: "Bear Lake Loop",
    type: "Hiking",
    location: { lat: 40.31196, lng: -105.64581 },
    difficulty: "Beginner",
    elevationGain: "45 ft",
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
    image:
      "https://www.rockymountainnationalpark.com/images/xl/20180910-19-08-17-lg.jpg",
  },
  {
    name: "Maroon Bells",
    id: 1014,
    trail: "Maroon Lake Scenic Loop Trail",
    type: "Hiking",
    location: { lat: 39.09991, lng: -106.94192 },
    difficulty: "Beginner",
    elevationGain: "160 ft",
    entrancePass: "Yes",
    gearNeeded: "No",
    camping: "Yes",
    image:
      "https://photos.smugmug.com/United-States/Colorado/Maroon-Bells/i-ZJWbfrR/0/873666a9/XL/IMG_2449-XL.jpg",
  },
  {
    name: "Bangor City Forest",
    id: 1015,
    trail: "East-West and Deer Trail Loop",
    type: "Hiking",
    location: { lat: 29.951722, lng: -95.237709 },
    difficulty: "Beginner",
    elevationGain: "39 ft",
    entrancePass: "No",
    gearNeeded: "No",
    camping: "Yes",
    image:
      "https://endlessmountains.wordpress.com/wp-content/uploads/2025/06/gm2.jpg",
  },
];

export { activities };
